version: 2
jobs:
  build:
    docker:

      - image: circleci/python:3.6.1

    working_directory: ~/haensel-ams

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv haensel-ams
            . haensel-ams/bin/activate
            make install
      - save_cache:
          paths:
            - ./haensel-ams
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run lint
          command: |
            . haensel-ams/bin/activate
            make lint